version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test-app
          command: ./node_modules/mocha/bin/mocha --exit
      - run:
          name: display-env
          command: echo $DOCKER_HUB_TRIG_URL
      - run:
          name: deploy-app
          branch: master
          command: curl -X POST -H "Content-Type:application/json" --data '{"build":true}' https://cloud.docker.com/api/build/v1/source/a867f8ea-fe9c-47c5-8aab-d0f4a04f68cb/trigger/0e4950cd-5564-47b7-ba13-c210c5f3eb3c/call/
