version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test-app
          command: ./node_modules/mocha/bin/mocha --exit
      - run:
          name: display-env
          command: echo $DOCKER_HUB_TRIG_URL
      - run:
          name: deploy-app
          branch: master
          command: $DOCKER_HUB_TRIG_URL
